# Pengantar {.unnumbered}

Selamat datang di buku "Strategi Arbitrase Kripto untuk Pemula".

Buku ini tidak benar-benar untuk pemula yang belum mengenal pemrograman, tapi ini pemula bagi teman-teman yang ingin belajar konsep arbitrase. Teman-teman akan diajak berkenalan dengan apa itu arbitrase dan apa saja strategi yang bisa kita pakai dalam arbitrase.

Kita juga akan berfokus membahas arbitrase di kripto karena itu adalah pasar yang ideal dengan likuiditas global dan berbagai instrumen pasarnya. Tentu informasi buku ini tidak hanya bisa dipakai di kripto, konsepnya tetap bisa diterapkan di pasar lain, seperti: saham, Forex, dan komoditas.

Saya selalu berharap teman-teman menikmati apa yang saya tulis dalam buku ini. Jangan segan memberi masukan jika masih ada kekurangan dalam buku ini yang perlu saya perbaiki.

Buku ini mungkin cuma membahas mengenai konsep dasar dari arbitrase, tapi jika kamu memerlukan layanan khusus seperti pelatihan atau konsultasi, jangan segan untuk terhubung dengan saya melalui kontak ini:

> **email**: moh.rosidi2610@gmail.com | **WA**: 082128770438